### ISSUE TITLE
Arbitrary birth-time reset

### ISSUE THREAD

**Issue by Yaksinikos** [CruiserOne/Astrolog#12]
MY Setup: 
wine on Linux
Astrolog750

Issue: Somewhy the birth-time manipulate ifself after importing a .aaf file.

How to reproduce:
- Create a new chart for:
18.12.1936 18:10 in "Marks, Russia"
- Export it as .aaf file
- import it again
- somewhy the time resets itself automatically to 6:10 ... but in file it is still correct

**Comment by CruiserOne** [comment]
This is a bug. The AAF file is correctly exported, but Astrolog isn't importing it back in correctly. Astrolog is incorrectly parsing beyond the "18:10" in the file, and seeing the "a" at the end of "Russia" as an "am" suffix, and so is seeing the time as 6:10am. Hack workaround: Put an underscore or other alternate character at the end of "Russia", so the time isn't seen as "am". This bug will be fixed in the next version.
