### ISSUE TITLE
Vedic Charts

### ISSUE THREAD

**Issue by Yaksinikos** [CruiserOne/Astrolog#13]
May to add mention to "North-Indian Chart" that is represents the "bhava chalit" system, while "South-Indian Chart" is the classic "raši" chart. (readme or in program would be it, as I think)
Actually/originally both kinds of representation are interchangeable, and are not dependent on the house-system used, whether it is a whole-sign or a vehlow/vedic/centered-equal house system.

Have been just little bit surprised to see different positions of sun in both charts, while randomly changing the chart style. 😄 ❤️

**Comment by CruiserOne** [comment]
Good idea, I will add references to "rasi" (zodiac sign based) versus "bhava chalit" (house positions) to the documentation for these two charts, to make their origin and distinction clearer.

Astrolog's South and North Indian charts are indeed mostly interchangeable, except they focus upon different things in non-Whole house systems. South Indian always displays one box per sign/rasi, which means houses will only be labelled too if Whole system is used (which means there's one box per house too). North Indian always displays one box per house, which means signs will only be labelled too if Whole is used (so there's one box per sign too).

Switching between South and North Indian shouldn't change the position of anything. Planets may change orientation due to the different rotation of the two charts. A planet's box may be labelled differently too, such as being in a Scorpio box versus a 10th house box. However when both sign and house are labeled, they should be the same for all planets (e.g. in Scorpio and 10th house box).
