### ISSUE TITLE
Configuration File Extension

### ISSUE THREAD

**Issue by Yaksinikos** [CruiserOne/Astrolog#14]
Is there a possibility to implement separated config-entries for
- "true lilith"
- "mean nodes"
- "Sideral Zodiac in Invariable Plane of Solar System"
inside astrolog.as
Would be handy.

**Comment by CruiserOne** [comment]
Astrolog's default settings file astrolog.as doesn't contain every setting in the program, but rather just a major subset of them. The "Sidereal Zodiac in Invariable Plane of Solar System" setting (-Ys command switch) was not automatically saved to this file, however I've added it so it will be in the next version. :)

Another setting "Compute True Instead of Mean Nodes and Lilith" (-Yn switch) is already saved to this file. This setting affects both Lilith and the Nodes. If you want True Lilith and Mean Nodes at the same time, that can still be done in Astrolog, but requires defining a custom object. To do this, turn off "Compute True Instead of Mean Nodes and Lilith" so the Nodes are mean, and then for true Lilith define a custom object in the "Object Customization" dialog to be "Moon pN" (or using the -YeOaN switch) which means make that object be the Moon's perigee point (i.e. Lilith) with the "Compute True Instead of Mean Nodes and Lilith" setting inverted for that object only. Object customizations are saved to astrolog.as, so that will cover the "true Lilith"+"mean nodes" part of the above.
