### ISSUE TITLE
Question on position files

### ISSUE THREAD

**Issue by tbikeev** [CruiserOne/Astrolog#23]
Hi Walter,

First, many thanks for the excellent software that has been accompanying me for nearly 30 years!

I came across a case where I'd like to run a comparison between a radix file and a 'position file,' which is a dump of a progressed radix, plus possibly some extra objects, such as syzygy or eclipse positions.

Here’s the process I followed:

1. **Step 1:** Perform a progression and store it with `-o0` into `positions.dat`, which contains several `-YF` lines.
2. **Step 2:** Add additional objects via `-YF` as needed.
3. **Step 3:** Read both `radix.dat` and `positions.dat` back, then perform aspect analysis between the two files. This is where I’m encountering an issue.

I’ve tried the following commands, OSX terminal:

- `-rt radix.dat positions.dat` (this shows a second wheel, but everything is jammed into the Aries 0° point)
- `-i radix.dat -i2 positions.dat` (this only shows one wheel)

So, my two questions are:

1. How do I correctly compare a chart defined by a date with one obtained from a position file (no date or space)?
2. How can I load them into slots `i1` and `i2` and analyze the relationship between them?

Cheers,  
Thomas

**Comment by CruiserOne** [comment]
Hello, and glad Astrolog has been serving you for so long! :) The above is a bug, in which the -r command switch isn't copying -YF switch positions into the second chart slot. There are three alternatives:

1) Use the Windows version, in which using the menu GUI to load position files works (because it bypasses the -r switch). 
2) Wait for the next version, in which this will be fixed.
3) Edit the source code and recompile. In astrolog.cpp, after line 2646 (which is "return fFalse;") insert the line: "cp2 = cp0;"

**Comment by tbikeev** [comment]
Thanks @CruiserOne !
