### ISSUE TITLE
Issue with AddTime function in xcharts2.cpp

### ISSUE THREAD

**Issue by tactipus** [CruiserOne/Astrolog#6]
Good evening,

I tried to compile the software when I get this error.

`xcharts2.cpp:1430:7: error: use of undeclared identifier 'AddTime'
AddTime(&ciCore, 4, z);
      ^`

I have never dealt with code in C++ before, and a Google search doesn't help.

**Comment by CruiserOne** [comment]
This only happens if Astrolog is compiled with "#ifdef GRAPH" on, and also if all of the interactive screen graphics options like "#ifdef X11" and "#ifdef WIN" are turned off. To avoid the problem, select different compilation options. To actually fix this so you can compile with those options, make the following three code changes: (1) In extern.h line 876 move the line "extern void AddTime..." up three lines so it’s no longer within the "#ifdef ISG" block. (2) In xscreen.cpp line 462 (right before the function definition "void AddTime") insert the line "#endif". (3) Also in xscreen.cpp line 533 (right after the final "}" line in the definition of AddTime) insert the line "#ifdef ISG".
